# Generated by Django 5.2 on 2025-04-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_date_of_birth_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lawyer', 'Lawyer'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
