# Generated by Django 5.2 on 2025-04-24 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_case_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesummary',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casesummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
