# Generated by Django 5.2 on 2025-04-24 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_casesummary_lawyer_alter_casesummary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
