# Generated by Django 5.2 on 2025-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appointment_isseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lawyer_type',
            field=models.CharField(blank=True, choices=[('criminal', 'Criminal Lawyer'), ('estate_planning', 'Estate Planning Lawyer'), ('tax', 'Tax Lawyer'), ('personal_injury', 'Personal Injury Lawyer'), ('corporate', 'Corporate Lawyer'), ('business', 'Business Lawyer'), ('intellectual_property', 'Intellectual Property Lawyer'), ('family', 'Family Lawyer')], help_text="Specify the type of lawyer if the role is 'lawyer'.", max_length=50, null=True),
        ),
    ]
